<?php

use yii\db\Migration;

class m230617_104711_stations_transfersDataInsert extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->batchInsert('{{%stations_transfers}}',
                           ["id", "station_id", "station_to_id", "type", "name", "code", "icon"],
                            [
    [
        'id' => 1,
        'station_id' => 20,
        'station_to_id' => 6,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 2,
        'station_id' => 6,
        'station_to_id' => 20,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 3,
        'station_id' => 21,
        'station_to_id' => 62,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 4,
        'station_id' => 62,
        'station_to_id' => 21,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 5,
        'station_id' => 21,
        'station_to_id' => 80,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 6,
        'station_id' => 80,
        'station_to_id' => 21,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 7,
        'station_id' => 53,
        'station_to_id' => 67,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 8,
        'station_id' => 67,
        'station_to_id' => 53,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 9,
        'station_id' => 55,
        'station_to_id' => 76,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 10,
        'station_id' => 76,
        'station_to_id' => 55,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 11,
        'station_id' => 62,
        'station_to_id' => 80,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 12,
        'station_id' => 80,
        'station_to_id' => 62,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 13,
        'station_id' => 63,
        'station_to_id' => 88,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 14,
        'station_id' => 88,
        'station_to_id' => 63,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 15,
        'station_id' => 17,
        'station_to_id' => 175,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 16,
        'station_id' => 175,
        'station_to_id' => 17,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 17,
        'station_id' => 17,
        'station_to_id' => 87,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 18,
        'station_id' => 87,
        'station_to_id' => 17,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 19,
        'station_id' => 19,
        'station_to_id' => 195,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 20,
        'station_id' => 195,
        'station_to_id' => 19,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 21,
        'station_id' => 23,
        'station_to_id' => 96,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 22,
        'station_id' => 96,
        'station_to_id' => 23,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 23,
        'station_id' => 307,
        'station_to_id' => 101,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 24,
        'station_id' => 101,
        'station_to_id' => 307,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 25,
        'station_id' => 40,
        'station_to_id' => 135,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 26,
        'station_id' => 135,
        'station_to_id' => 40,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 27,
        'station_id' => 40,
        'station_to_id' => 151,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 28,
        'station_id' => 151,
        'station_to_id' => 40,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 29,
        'station_id' => 6,
        'station_to_id' => 57,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 30,
        'station_id' => 57,
        'station_to_id' => 6,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 31,
        'station_id' => 41,
        'station_to_id' => 94,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 32,
        'station_id' => 94,
        'station_to_id' => 41,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 33,
        'station_id' => 41,
        'station_to_id' => 167,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 34,
        'station_id' => 167,
        'station_to_id' => 41,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 35,
        'station_id' => 42,
        'station_to_id' => 92,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 36,
        'station_id' => 92,
        'station_to_id' => 42,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 37,
        'station_id' => 130,
        'station_to_id' => 198,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 38,
        'station_id' => 198,
        'station_to_id' => 130,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 39,
        'station_id' => 309,
        'station_to_id' => 248,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 40,
        'station_id' => 248,
        'station_to_id' => 309,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 41,
        'station_id' => 55,
        'station_to_id' => 98,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 42,
        'station_id' => 98,
        'station_to_id' => 55,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 43,
        'station_id' => 62,
        'station_to_id' => 152,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 44,
        'station_id' => 152,
        'station_to_id' => 62,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 45,
        'station_id' => 3,
        'station_to_id' => 89,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 46,
        'station_id' => 89,
        'station_to_id' => 3,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 47,
        'station_id' => 72,
        'station_to_id' => 271,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 48,
        'station_id' => 271,
        'station_to_id' => 72,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 49,
        'station_id' => 76,
        'station_to_id' => 98,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 50,
        'station_id' => 98,
        'station_to_id' => 76,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 51,
        'station_id' => 84,
        'station_to_id' => 86,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 52,
        'station_id' => 86,
        'station_to_id' => 84,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 53,
        'station_id' => 87,
        'station_to_id' => 175,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 54,
        'station_id' => 175,
        'station_to_id' => 87,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 55,
        'station_id' => 134,
        'station_to_id' => 99,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 56,
        'station_id' => 99,
        'station_to_id' => 134,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 57,
        'station_id' => 135,
        'station_to_id' => 151,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 58,
        'station_id' => 151,
        'station_to_id' => 135,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 59,
        'station_id' => 138,
        'station_to_id' => 90,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 60,
        'station_id' => 90,
        'station_to_id' => 138,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 61,
        'station_id' => 138,
        'station_to_id' => 166,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 62,
        'station_id' => 166,
        'station_to_id' => 138,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 63,
        'station_id' => 91,
        'station_to_id' => 137,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 64,
        'station_id' => 137,
        'station_to_id' => 91,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 65,
        'station_id' => 140,
        'station_to_id' => 178,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 66,
        'station_id' => 178,
        'station_to_id' => 140,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 67,
        'station_id' => 147,
        'station_to_id' => 300,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 68,
        'station_id' => 300,
        'station_to_id' => 147,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 69,
        'station_id' => 94,
        'station_to_id' => 167,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 70,
        'station_id' => 167,
        'station_to_id' => 94,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 71,
        'station_id' => 97,
        'station_to_id' => 95,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 72,
        'station_id' => 95,
        'station_to_id' => 97,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 73,
        'station_id' => 165,
        'station_to_id' => 177,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 74,
        'station_id' => 177,
        'station_to_id' => 165,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 75,
        'station_id' => 166,
        'station_to_id' => 90,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 76,
        'station_id' => 90,
        'station_to_id' => 166,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 77,
        'station_id' => 111,
        'station_to_id' => 199,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 78,
        'station_id' => 199,
        'station_to_id' => 111,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 79,
        'station_id' => 176,
        'station_to_id' => 89,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 80,
        'station_id' => 89,
        'station_to_id' => 176,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 81,
        'station_id' => 141,
        'station_to_id' => 102,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 82,
        'station_id' => 102,
        'station_to_id' => 141,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 83,
        'station_id' => 148,
        'station_to_id' => 174,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 84,
        'station_id' => 174,
        'station_to_id' => 148,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 85,
        'station_id' => 152,
        'station_to_id' => 21,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 86,
        'station_id' => 21,
        'station_to_id' => 152,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 87,
        'station_id' => 154,
        'station_to_id' => 93,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 88,
        'station_id' => 93,
        'station_to_id' => 154,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 89,
        'station_id' => 185,
        'station_to_id' => 201,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 90,
        'station_id' => 201,
        'station_to_id' => 185,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 91,
        'station_id' => 139,
        'station_to_id' => 225,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 92,
        'station_id' => 225,
        'station_to_id' => 139,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 93,
        'station_id' => 3,
        'station_to_id' => 176,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 94,
        'station_id' => 176,
        'station_to_id' => 3,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 95,
        'station_id' => 53,
        'station_to_id' => 231,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 96,
        'station_id' => 231,
        'station_to_id' => 53,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 97,
        'station_id' => 118,
        'station_to_id' => 188,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 98,
        'station_id' => 188,
        'station_to_id' => 118,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 99,
        'station_id' => 124,
        'station_to_id' => 292,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 100,
        'station_id' => 292,
        'station_to_id' => 124,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 101,
        'station_id' => 121,
        'station_to_id' => 288,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 102,
        'station_id' => 288,
        'station_to_id' => 121,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 103,
        'station_id' => 24,
        'station_to_id' => 270,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 104,
        'station_id' => 270,
        'station_to_id' => 24,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 105,
        'station_id' => 189,
        'station_to_id' => 266,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 106,
        'station_id' => 266,
        'station_to_id' => 189,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 107,
        'station_id' => 22,
        'station_to_id' => 284,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 108,
        'station_id' => 284,
        'station_to_id' => 22,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 109,
        'station_id' => 75,
        'station_to_id' => 196,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 110,
        'station_id' => 196,
        'station_to_id' => 75,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 111,
        'station_id' => 45,
        'station_to_id' => 334,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 112,
        'station_id' => 334,
        'station_to_id' => 45,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 113,
        'station_id' => 128,
        'station_to_id' => 224,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 114,
        'station_id' => 224,
        'station_to_id' => 128,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 115,
        'station_id' => 47,
        'station_to_id' => 315,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 116,
        'station_id' => 315,
        'station_to_id' => 47,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 117,
        'station_id' => 164,
        'station_to_id' => 297,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 118,
        'station_id' => 297,
        'station_to_id' => 164,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 119,
        'station_id' => 101,
        'station_to_id' => 226,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 120,
        'station_id' => 226,
        'station_to_id' => 101,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 121,
        'station_id' => 307,
        'station_to_id' => 226,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 122,
        'station_id' => 226,
        'station_to_id' => 307,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 123,
        'station_id' => 182,
        'station_to_id' => 193,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 124,
        'station_id' => 193,
        'station_to_id' => 182,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 125,
        'station_id' => 117,
        'station_to_id' => 245,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 126,
        'station_id' => 245,
        'station_to_id' => 117,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 127,
        'station_id' => 324,
        'station_to_id' => 139,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 128,
        'station_id' => 139,
        'station_to_id' => 324,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 129,
        'station_id' => 122,
        'station_to_id' => 327,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 130,
        'station_id' => 327,
        'station_to_id' => 122,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 131,
        'station_id' => 327,
        'station_to_id' => 273,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 132,
        'station_id' => 273,
        'station_to_id' => 327,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 133,
        'station_id' => 211,
        'station_to_id' => 338,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 134,
        'station_id' => 338,
        'station_to_id' => 211,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 135,
        'station_id' => 50,
        'station_to_id' => 243,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 136,
        'station_id' => 243,
        'station_to_id' => 50,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 137,
        'station_id' => 187,
        'station_to_id' => 223,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 138,
        'station_id' => 223,
        'station_to_id' => 187,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 139,
        'station_id' => 67,
        'station_to_id' => 231,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 140,
        'station_id' => 231,
        'station_to_id' => 67,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 141,
        'station_id' => 181,
        'station_to_id' => 310,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 142,
        'station_id' => 310,
        'station_to_id' => 181,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 143,
        'station_id' => 54,
        'station_to_id' => 230,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 144,
        'station_id' => 230,
        'station_to_id' => 54,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 145,
        'station_id' => 328,
        'station_to_id' => 228,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 146,
        'station_id' => 228,
        'station_to_id' => 328,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 147,
        'station_id' => 324,
        'station_to_id' => 225,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 148,
        'station_id' => 225,
        'station_to_id' => 324,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 149,
        'station_id' => 142,
        'station_to_id' => 282,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 150,
        'station_id' => 282,
        'station_to_id' => 142,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 151,
        'station_id' => 74,
        'station_to_id' => 272,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 152,
        'station_id' => 272,
        'station_to_id' => 74,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 153,
        'station_id' => 328,
        'station_to_id' => 287,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 154,
        'station_id' => 287,
        'station_to_id' => 328,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 155,
        'station_id' => 180,
        'station_to_id' => 283,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 156,
        'station_id' => 283,
        'station_to_id' => 180,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 157,
        'station_id' => 293,
        'station_to_id' => 281,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 158,
        'station_id' => 281,
        'station_to_id' => 293,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 159,
        'station_id' => 75,
        'station_to_id' => 333,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 160,
        'station_id' => 333,
        'station_to_id' => 75,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 161,
        'station_id' => 196,
        'station_to_id' => 333,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 162,
        'station_id' => 333,
        'station_to_id' => 196,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 163,
        'station_id' => 74,
        'station_to_id' => 228,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 164,
        'station_id' => 228,
        'station_to_id' => 74,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 165,
        'station_id' => 59,
        'station_to_id' => 329,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 166,
        'station_id' => 329,
        'station_to_id' => 59,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 167,
        'station_id' => 325,
        'station_to_id' => 39,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 168,
        'station_id' => 39,
        'station_to_id' => 325,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 169,
        'station_id' => 75,
        'station_to_id' => 228,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 170,
        'station_id' => 228,
        'station_to_id' => 75,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 171,
        'station_id' => 120,
        'station_to_id' => 257,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 172,
        'station_id' => 257,
        'station_to_id' => 120,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 173,
        'station_id' => 89,
        'station_to_id' => 260,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 174,
        'station_id' => 260,
        'station_to_id' => 89,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 175,
        'station_id' => 295,
        'station_to_id' => 251,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 176,
        'station_id' => 251,
        'station_to_id' => 295,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 177,
        'station_id' => 177,
        'station_to_id' => 304,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 178,
        'station_id' => 304,
        'station_to_id' => 177,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 179,
        'station_id' => 165,
        'station_to_id' => 304,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 180,
        'station_id' => 304,
        'station_to_id' => 165,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 181,
        'station_id' => 11,
        'station_to_id' => 261,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 182,
        'station_id' => 261,
        'station_to_id' => 11,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 183,
        'station_id' => 122,
        'station_to_id' => 273,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 184,
        'station_id' => 273,
        'station_to_id' => 122,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 185,
        'station_id' => 126,
        'station_to_id' => 256,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 186,
        'station_id' => 256,
        'station_to_id' => 126,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 187,
        'station_id' => 71,
        'station_to_id' => 229,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 188,
        'station_id' => 229,
        'station_to_id' => 71,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 189,
        'station_id' => 267,
        'station_to_id' => 264,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 190,
        'station_id' => 264,
        'station_to_id' => 267,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 191,
        'station_id' => 251,
        'station_to_id' => 274,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 192,
        'station_id' => 274,
        'station_to_id' => 251,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 193,
        'station_id' => 123,
        'station_to_id' => 227,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 194,
        'station_id' => 227,
        'station_to_id' => 123,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 195,
        'station_id' => 156,
        'station_to_id' => 286,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 196,
        'station_id' => 286,
        'station_to_id' => 156,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 197,
        'station_id' => 121,
        'station_to_id' => 289,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 198,
        'station_id' => 289,
        'station_to_id' => 121,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 199,
        'station_id' => 12,
        'station_to_id' => 278,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 200,
        'station_id' => 278,
        'station_to_id' => 12,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 201,
        'station_id' => 143,
        'station_to_id' => 265,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 202,
        'station_id' => 265,
        'station_to_id' => 143,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 203,
        'station_id' => 179,
        'station_to_id' => 283,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 204,
        'station_id' => 283,
        'station_to_id' => 179,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 205,
        'station_id' => 106,
        'station_to_id' => 336,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 206,
        'station_id' => 336,
        'station_to_id' => 106,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 207,
        'station_id' => 4,
        'station_to_id' => 337,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 208,
        'station_id' => 337,
        'station_to_id' => 4,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 209,
        'station_id' => 61,
        'station_to_id' => 263,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 210,
        'station_id' => 263,
        'station_to_id' => 61,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 211,
        'station_id' => 136,
        'station_to_id' => 255,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 212,
        'station_id' => 255,
        'station_to_id' => 136,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 213,
        'station_id' => 125,
        'station_to_id' => 254,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 214,
        'station_id' => 254,
        'station_to_id' => 125,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 215,
        'station_id' => 133,
        'station_to_id' => 269,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 216,
        'station_id' => 269,
        'station_to_id' => 133,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 217,
        'station_id' => 63,
        'station_to_id' => 344,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 218,
        'station_id' => 344,
        'station_to_id' => 63,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 219,
        'station_id' => 295,
        'station_to_id' => 290,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 220,
        'station_id' => 290,
        'station_to_id' => 295,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 221,
        'station_id' => 341,
        'station_to_id' => 231,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 222,
        'station_id' => 231,
        'station_to_id' => 341,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 223,
        'station_id' => 53,
        'station_to_id' => 341,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 224,
        'station_id' => 341,
        'station_to_id' => 53,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 225,
        'station_id' => 67,
        'station_to_id' => 341,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 226,
        'station_id' => 341,
        'station_to_id' => 67,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 227,
        'station_id' => 181,
        'station_to_id' => 343,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 228,
        'station_id' => 343,
        'station_to_id' => 181,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 229,
        'station_id' => 291,
        'station_to_id' => 223,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 230,
        'station_id' => 223,
        'station_to_id' => 291,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 231,
        'station_id' => 187,
        'station_to_id' => 291,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
    [
        'id' => 232,
        'station_id' => 291,
        'station_to_id' => 187,
        'type' => 'metro',
        'name' => '',
        'code' => null,
        'icon' => '',
    ],
]
        );
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%stations_transfers}} CASCADE');
    }
}
